#!/bin/sh
# File: /etc/uci-defaults/70-rootpt-resize

if [ ! -e /etc/rootpt-resize ] \
   && type parted > /dev/null 2>&1 \
   && lock -n /var/lock/root-resize
then
    ROOT_BLK="$(readlink -f /sys/dev/block/"$(awk -e '$9=="/dev/root"{print $3}' /proc/self/mountinfo)")"
    ROOT_DISK="/dev/$(basename "${ROOT_BLK%/*}")"
    ROOT_PART="${ROOT_BLK##*[^0-9]}"

    parted -f -s "${ROOT_DISK}" resizepart "${ROOT_PART}" 100%
    mount_root

    touch /etc/rootpt-resize

    if [ -e /boot/cmdline.txt ]; then
        NEW_UUID=$(blkid "${ROOT_DISK}p${ROOT_PART}" | sed -n 's/.*PARTUUID="\([^"]*\)".*/\1/p')
        [ -n "$NEW_UUID" ] && sed -i "s/PARTUUID=[^ ]*/PARTUUID=${NEW_UUID}/" /boot/cmdline.txt
    fi

    reboot
    exit 0
fi

exit 1