#!/bin/sh
# File: /etc/uci-defaults/80-rootfs-resize

if [ ! -e /etc/rootfs-resize ] \
   && [ -e /etc/rootpt-resize ] \
   && type losetup > /dev/null 2>&1 \
   && type resize2fs > /dev/null 2>&1 \
   && lock -n /var/lock/root-resize
then
    ROOT_BLK="$(readlink -f /sys/dev/block/"$(awk -e '$9=="/dev/root"{print $3}' /proc/self/mountinfo)")"
    ROOT_DEV="/dev/${ROOT_BLK##*/}"

    LOOP_DEV="$(awk -e '$5=="/overlay"{print $9}' /proc/self/mountinfo)"
    if [ -z "${LOOP_DEV}" ]; then
        LOOP_DEV="$(losetup -f)"
        losetup "${LOOP_DEV}" "${ROOT_DEV}"
    fi

    resize2fs -f "${LOOP_DEV}"
    mount_root

    touch /etc/rootfs-resize
    apk del parted resize2fs e2fsprogs blkid losetup
    rm -f /etc/rootpt-resize /etc/rootfs-resize
    reboot
    exit 0
fi

exit 1
