#!/bin/sh
# File: /etc/uci-defaults/80-rootfs-resize

if [ ! -e /etc/rootfs-resize ] \
   && [ -e /etc/rootpt-resize ] \
   && type losetup > /dev/null \
   && type resize2fs > /dev/null \
   && lock -n /var/lock/root-resize
then
    # 获取根设备信息
    ROOT_BLK="$(readlink -f /sys/dev/block/"$(awk -e '$9=="/dev/root"{print $3}' /proc/self/mountinfo)")"
    ROOT_DEV="/dev/${ROOT_BLK##*/}"

    # 检查 overlay 是否使用了 loop 设备
    LOOP_DEV="$(awk -e '$5=="/overlay"{print $9}' /proc/self/mountinfo)"
    if [ -z "${LOOP_DEV}" ]
    then
        LOOP_DEV="$(losetup -f)"
        losetup "${LOOP_DEV}" "${ROOT_DEV}"
    fi

    # 扩展文件系统
    resize2fs -f "${LOOP_DEV}"

    # 重新挂载根文件系统
    mount_root
    done

    # 标记文件系统已调整
    touch /etc/rootfs-resize

    # 再次重启，使所有更改生效
    reboot
fi

exit 1