#!/bin/sh /etc/rc.common
START=00
STOP=

start() {
    if [ -b /dev/sda4 ]; then
        mount -t ext4 /dev/sda4 /mnt/sda4
        mount -t overlay overlay -o lowerdir=/rom,upperdir=/mnt/sda4/upper,workdir=/mnt/sda4/work /overlay
    fi
}