#!/bin/sh
[ "$ACTION" = "ifup" ] || exit 0

case "$INTERFACE" in
    eth0)
        cores=$(grep -c ^processor /proc/cpuinfo)
        rps_mask_no_cpu0=$(printf "%x" $(( ((1 << cores) - 1) & ~1 )))
        q=0
        while [ -d "/sys/class/net/eth0/queues/rx-$q" ]; do
            echo "$rps_mask_no_cpu0" > "/sys/class/net/eth0/queues/rx-$q/rps_cpus"
            q=$((q + 1))
        done
        ;;
esac